### ISSUE TITLE
Have adapter-hub be self contained and not depend on a version of transformers

### ISSUE THREAD

**Issue by AmirAktify** [adapter-hub/adapters#119]
# 🚀 Feature request

1. Request: Have adapter-hub be a fork off of huggingface, and its own repository rather than depend on a specific version of Huggingface or clash with it's installation.

## Motivation
1. Huggingface is an industry / commercially maintained repository with new models and changes being released constantly. As such, it's realistic / reasonable that AdapterHub will always be many versions behind.
2. However, this then causes breaks, where I can't use the latest AdapterHub in the same virtualenv or python service as for example HuggingFace 4.x.
3. In particular, for the kind of usecases adapter-hubs envision - serving adapters of many models in an efficient production environment - ease of use and compatibility with main HuggingFace is beneficial. And would encourage usage and adoption by the broader community of practitioners.
4. Of course, there'll still be feature requests where people want adapter-hub to be up to the date with the latest and greatest Huggingface models, and its not feasible with the maintainer's other commitments. But at least the discrepancy then wouldn't be breaking / preclude their use together.

## Your contribution
I could do the switchover once, and submit a PR moving over to this paradigm, if the repository owners think its a good idea. I know it might be a lot of work, and of course I'd be willing to put most of it in. It might be as simple as just putting the package in a separate namespace however.

**Comment by calpt** [comment]
@AmirAktify thanks a lot for your thoughts on this. I totally understand and agree with your reasoning. Keeping up with the latest releases from HF is difficult, as we definitely don't have nowhere near the manpower they have. The issue of not being able to install transformers and adapter-transformers has been brought up before and we understand why that is desirable.

Our current design choice is led by two factors. First, we aimed to make switching between transformers and adapter-transformers as simple as possible, thus designing it as a drop-in replacement. Second, we didn't want to diverge too far from the original transformers implementation. This makes syncing new upstream changes easier and leaves the possibility to merge our changes back to the original library. Going forward, preparing adapter-transformers for a merge back into transformers (as discussed in #65) or evolving it into a fully independent library (as you suggest) are the two possible ways.

On your concrete suggestion of a simple namespace change, I'm not sure how much that would complicate pulling new changes from HF in the future as it introduces a lot more differences between our and HF's codebase.

But regarding all points, we're very open to any thoughts and suggestions on the best way going forward. (Maybe @JoPfeiff also wants to weigh in on this.)

**Comment by dtuggener** [comment]
I'm having installation issues related to this:
`adapter-transformers 1.1.1 requires tokenizers==0.9.3, but you have tokenizers 0.10.1 which is incompatible.`
If I downgrade to `tokenizers==0.9.3`, transformers 4.3.3. complains:
`transformers 4.3.3 requires tokenizers<0.11,>=0.10.1, but you have tokenizers 0.9.3 which is incompatible.`

**Comment by calpt** [comment]
Closing this issues as this request has been implemented with the new _Adapters_ library now hosted in this repo. See https://adapterhub.ml/blog/2023/11/introducing-adapters/ and #584 for more context.
