### ISSUE TITLE
New release date for AdapterHub

### ISSUE THREAD

**Issue by hchoi-moveworks** [adapter-hub/adapters#237]
When is the new release date of Adapterhub planned?

Current release 2.1.2 contains bug in handling of `DataParallel` which prohibits us to use multiple GPU's [1]

[1]: https://github.com/Adapter-Hub/adapter-transformers/issues/227

**Comment by calpt** [comment]
Hey @hchoi-moveworks, sorry for the delay with the new release. It's almost finished and will be available within the next seven days.
