### ISSUE TITLE
Support for LLaMa - LlamaForCausalLM

### ISSUE THREAD

**Issue by dittops** [adapter-hub/adapters#538]
Do we have support for LLaMa? If not, is that in the pipeline for development?

**Comment by hSterz** [comment]
Hey @dittops, we have LLaMa in the pipeline for development, but we are currently working on other exciting changes, so I can't make an estimation on when we will be able to add the support for LLaMa.
I am going to leave this pull request open and notify you when we have an update on the LLaMa model.

**Comment by ydennisy** [comment]
@dittops @hSterz hello!

So HF already has LLaMa, I therefore assume to include it would not be too hard? In either case I would be interested to see if I could help there. Would you happen to have a guide for how to integrate a new model into adapaters?

All the best,
D

**Comment by lenglaender** [comment]
@ydennisy, you can find detailed instructions on how to add adapters to a model in our documentation at this link: https://docs.adapterhub.ml/contributing/adding_adapters_to_a_model.html

We highly appreciate any contributions from the community, so your help would be greatly welcomed!

**Comment by hSterz** [comment]
Hey @ydennisy, we always love to see contributions from the community. In this particular case, we are currently working on a major refactoring (including breaking changes that would affect the LLaMa implementation). Therefore, it might make sense to wait till after the refactoring with the implementation.

**Comment by scorixear** [comment]
Just want to comment here to let you know, that there exists interest in this from more people.
I loved your paper and would really want to use this in combination with llama for my master thesis!

**Comment by calpt** [comment]
Just as a short update on this: Llama is already included in the development version of the next major release of our library. See #584 for more context.
