### ISSUE TITLE
Default configuration for training

### ISSUE THREAD

**Issue by FahadEbrahim** [adapter-hub/adapters#611]
Hi, 

Just a quick question, for training an adapter, what are the default adapter configurations (Method or type)? 

Thanks.

**Comment by hSterz** [comment]
Hello @FahadEbrahim , the default configuration that is used if you call `add_adapter`without specifying the config parameter is the `seq_bn` config (previously named `pfeiffer`config). To use a different configuration just pass the corresponding string as the config parameter ([docs](https://docs.adapterhub.ml/overview.html#table-of-adapter-methods)).

**Comment by FahadEbrahim** [comment]
Thank you both @calpt and @hSterz for your assistance.
