### ISSUE TITLE
What is the default adapter setup?

### ISSUE THREAD

**Issue by Eugleo** [adapter-hub/adapters#615]
I poured through the docs and the source code, but then I figured I might as well just ask here. Which adapter is loaded when I run the following code?

```python
model.add_adapter("name")
model.train_adapter("name")
model.set_active_adapters("name")
```

**Comment by FahadEbrahim** [comment]
Hi @Eugleo 
I asked the same question previously. Here is the thread with the answer:
https://github.com/adapter-hub/adapters/issues/611
