### ISSUE TITLE
Transformers 4.35.0 Snyk Vulnerability

### ISSUE THREAD

**Issue by SSamDav** [adapter-hub/adapters#647]
Hi,

As the title mention the transformers 4.35 has a vulnerability that was reported [here](https://security.snyk.io/vuln/SNYK-PYTHON-TRANSFORMERS-6135747). 
They advice us to update for the version 4.36, I just saw a [daft PR](https://github.com/adapter-hub/adapters/pull/617) that was open to 2 months ago. Do you need help updating the transformers to the next minor?

**Comment by calpt** [comment]
Thanks for bringing this up and oferring help! I was just working on some last issues for upgrading to v4.36.x, the PR should be merged shortly.
