### ISSUE TITLE
export onnx

### ISSUE THREAD

**Issue by aixuedegege** [adapter-hub/adapters#656]
# 🚀 Feature request

export to onnx

## Motivation

I have trained a model with fusion adapters, and I want to depoly this model to triton. Is there any good ways to export the model to onnx? I tried to export, but it accuracy is very different from zhe origin torch version.

**Comment by calpt** [comment]
Hey, unfortunately, exporting to onnx is currently not supported. This request is already tracked in #224, closing this issue as duplicate.
