### ISSUE TITLE
Cannot automatically convert prediction head of model class RobertaAdapterModel to flex head.

### ISSUE THREAD

**Issue by swoldemichael** [adapter-hub/adapters#662]
I was trying to try out my adapter model on the serverless inference API on Hugging Face, but the prediction head can not be converted to flex head. This would be good for prototyping. Perhaps, consider conversion for all models supported by adapters.

![Screenshot 2024-03-24 at 22-21-58 solwol_my-awesome-adapter · Hugging Face](https://github.com/adapter-hub/adapters/assets/37008415/94bdcdb9-280b-4af6-b8f8-099e1563e4d2)

**Comment by calpt** [comment]
Thanks for bringing this up, I think the inference API has not been updated to the new library yet, we will look into this!

**Comment by calpt** [comment]
This is being fixed in https://github.com/huggingface/api-inference-community/pull/422.

**Comment by calpt** [comment]
Should be fixed now with merge of the PR mentioned.
