### ISSUE TITLE
Total Parameter added to original model

### ISSUE THREAD

**Issue by km5ar** [adapter-hub/adapters#672]
Is there anyway we can calculate the total parameter added to original model?

**Comment by lenglaender** [comment]
Hi @km5ar,
to get a summary of the currently added adapters, you can use the `adapter_summary()` function like this:
```python
print(model.adapter_summary())
```
For an example script & output, see here: https://github.com/adapter-hub/adapters/pull/371
You can then sum up the "#Param" column values to get the total number of parameters added.

Alternatively, if you want a function that directly returns the total number of added parameters, you could write a new function based on the implementation of `adapter_summary()`. This would need just very few changes; the relevant part in the code is here: https://github.com/adapter-hub/adapters/blob/35fd1c2e55060e43a9759989793060cd6f9309ef/src/adapters/model_mixin.py#L1033-L1050
