### ISSUE TITLE
Looking forward to support for SAM

### ISSUE THREAD

**Issue by SHEN2BAIYI** [adapter-hub/adapters#713]
Hi, do you have plans to support SAM?

**Comment by TimoImhof** [comment]
Hey @SHEN2BAIYI,

thank you for your request; you mean the Segment Anything Model (SAM) from Meta, right?
Currently, we don't have any concrete plans to support this model.

However, we always value community input on potential new features, so we'll add it to our list of future to-dos.
Also, we always encourage community contributions, so if you're particularly interested in SAM integration, you're very welcome to start implementing it as a community contribution and open a PR.

I will close this issue as complete for now; if, in the future, the community or our team decides to add support for SAM, we will link back to this issue.
