### ISSUE TITLE
Move master to main

### ISSUE THREAD

**Issue by jonhilgart22** [adapter-hub/adapters#82]
# 🚀 Feature request

## Motivation

Given the historical baggage associated with the 'Master' branch, I propose moving to the main branch.

[https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main](https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main)

**Comment by calpt** [comment]
Done with switch to new "adapters" codebase.
